language: c

services:
  - docker

before_install:
  - docker build -t icbi/quantiseq:latest .

script:
  - echo "No testing for now. "

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
