language: c

services:
  - docker

before_install:
  - wget https://github.com/icbi-lab/quanTIseq/releases/download/v2.0.0/hg19_M_rCRS_kallisto.idx -O quantiseq/kallisto/hg19_M_rCRS_kallisto.idx
  - docker build -t icbi/quantiseq2:latest .

script:
  - FORCE_DOCKER=1 ./quanTIseq_pipeline.sh --outputdir=/tmp  --inputfile=test/rnaSeqInfoFile_singlesample.txt
  - FORCE_DOCKER=1 ./quanTIseq_pipeline.sh --outputdir=/tmp  --inputfile=test/rnaSeqInfoFile.txt


deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
