language: c

services:
  - docker

before_install:
  - wget https://github.com/icbi-lab/quanTIseq/releases/download/v2.0.0/hg19_M_rCRS_kallisto.idx -O quantiseq/kallisto/hg19_M_rCRS_kallisto.idx
  - docker build -t icbi/quantiseq2:latest .

script:
  - FORCE_DOCKER=1 ./quanTIseq_pipeline.sh --outputdir=/tmp  --inputfile=test/rnaSeqInfoFile_singlesample.txt --prefix=ss
  - diff test/Output_testfiles/ss_cell_fractions.txt /tmp/ss_cell_fractions.txt
  - diff test/Output_testfiles/ss_gene_tpm.txt /tmp/ss_gene_tpm.txt
  - FORCE_DOCKER=1 ./quanTIseq_pipeline.sh --outputdir=/tmp  --inputfile=test/rnaSeqInfoFile.txt
  - diff test/Output_testfiles/quanTIseq_cell_fractions.txt /tmp/quanTIseq_cell_fractions.txt
  - diff test/Output_testfiles/quanTIseq_gene_tpm.txt /tmp/quanTIseq_gene_tpm.txt


deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
